### ISSUE TITLE
auto approve/merge patch updates from dependabot in go repositories

### ISSUE THREAD

**Issue by kernelsam** [Senzing/build-resources#4]
**Is your feature request related to a problem? Please describe.**
Remove manual intervention requirement to review and merge patch version update PRs opened by dependabot on repositories where we are confident in our testing and status checks to catch potential issues.  

**Describe the solution you'd like**
Auto approve and merge patch version PRs opened by dependabot with a shared github workflow.
[See Github Documentation for details](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request).

**Additional context**
Initial POC [PR](https://github.com/kernelsam/dep-test/pull/1) and [workflow](https://github.com/kernelsam/shared-workflows/blob/main/.github/workflows/dependabot-automation.yml)

# Action Items

- [x] #5
- [x] #6
- [x] Senzing/go-common#38
- [x] Senzing/go-databasing#37
- [x] Senzing/go-grpcing#7
- [x] Senzing/go-logging#70
- [x] Senzing/go-messaging#14
- [x] Senzing/go-observing#32
- [x] Senzing/go-queuing#8
- [x] Senzing/go-sdk-abstract-factory#60
- [x] Senzing/knowledge-base#58
- [x] Senzing/template-go#49
- [x] #12 
- [x] Senzing/g2-sdk-go#83
- [x] Senzing/g2-sdk-go-base#58
- [x] Senzing/g2-sdk-go-grpc#66
- [x] Senzing/g2-sdk-go-mock#47
- [x] Senzing/senzing-tools#70
- [x] Senzing/serve-http#8
- [x] Senzing/serve-grpc#126
- [x] Senzing/go-rest-api-service#13
- [x] Senzing/observe#20
- [x] Senzing/init-database#97

## Change repository branch settings to require status checks to pass before merging.

1. On repository home page, click `Settings` tab.
    a. Click `Branches` in the left side nav.
    b. Click `Edit` button for the `main` branch protection rule.
    c. Check `Require status checks to pass before merging`
    d. Check `Require branches to be up to date before merging`
    e. Search and add **_ALL_** status checks 
    f. Confirm `Do not allow bypassing the above settings` is checked

## Change repository settings to enable auto merge.

Note: [See docs for additional details on this setting](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request). 
Individual PRs passing all required status checks will have the auto merge button, but will **_not_** be automatically merged until selected. Auto merge button is only visible when status checks are still in progress or failing.
```
After you enable auto-merge for a pull request, if someone who does not have write permissions to the repository pushes new changes to the head branch or switches the base branch of the pull request, auto-merge will be disabled.
```

1. On repository home page, click `Settings` tab.
    a. Check `Allow auto-merge`

### _**Alternative Approach**_

* reconfigure workflows to handle status check logic (i.e. all building, testing, etc. runs and is successful before approval and merge steps) and then use merge without the `—auto` flag. [See docs for details on flag.](https://cli.github.com/manual/gh_pr_merge)
* Concerns: anyone can modify the workflows files and if a change or mistake is missed in the review process it could potentially cause issues. 

## Change repository settings allow GitHub Actions to create and approve pull requests.

1. On repository home page, click `Settings` tab.
    a. Click `Actions` > `General` in the left side nav.
    b. Confirm  `Allow GitHub Actions to create and approve pull requests` is checked

## Codeowners configuration

* See discussion: https://github.com/orgs/community/discussions/23064
* [Recommended action is to use a different token for approval](https://stackoverflow.com/questions/70664840/automatic-merging-of-dependabot-generated-pull-request-with-codeowners-file-and)
* [Adding a dependabot token for repositories](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/configuring-access-to-private-registries-for-dependabot#adding-an-organization-secret-for-dependabot).

## Current (5.25.2023) Go Repository List

* `go-common`
* `go-databasing`
* `go-grpcing`
* `go-logging`
* `go-messaging`
* `go-observing`
* `go-queuing`
* `go-sdk-abstract-factory`

**Comment by kernelsam** [comment]
Issue encountered in testing code owner approval:[ dependabot actions cannot access secrets](https://github.com/dependabot/dependabot-core/issues/3253). Investigating suggested workarounds and alternatives with security considerations.

**Comment by kernelsam** [comment]
Notes from working session with Ron and Michael:
- discussed codeowners token and walked through config 
- discussed enabling auto merge and changes that will be seen in the UI after
- reviewed signing commits locally

**Comment by kernelsam** [comment]
Closing this as completed. Opened #42 to track GraphQL error
